### ISSUE TITLE
Why is gl_SubgroupSize restricted to be a power of 2?

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/GLSL#45] opened 2018-12-07 14:44 UTC
We have a target that executes a non-power-of-2 number of threads in lock-step.  It would be natural to make a subgroup have one member per thread, but we are not able to because **GL_KHR_shader_subgroup** states:

> If the extension GL_KHR_shader_subgroup_basic is enabled, the variable
>     <gl_SubgroupSize> is the number of invocations within a subgroup, and its
> value is always a power of 2. 

Why is there a restriction that it must be a power of 2?  Is there any real need for that?

(As far as I can see, neither SPIR-V nor vulkan have this restriction, it is only in GLSL, so we could in theory have shaders written in other languages running on vulkan with a non-power-of-2 subgroup size.)

**Comment by stevec611** [comment] 2018-12-10 11:02
> If there's no restriction in SPIR-V or Vulkan then IMO there shouldn't be in GLSL

Though I suppose the reality right now is that if GLSL requires power-of-two, then no vulkan implementation would choose to set VkPhysicalDeviceSubgroupProperties.subgroupSize to a non-power-of-two, since that would prevent it from supporting GLSL subgroups.

**Comment by nhaehnle** [comment] 2019-08-21 08:10
If we were to relax this, we'd have to be particularly careful about what happens with ClusteredReduce operations.

**Comment by gnl21** [comment] 2019-08-21 09:40
This has been discussed internally, but I don't think I can copy any of that discussion here without permission. Labelling as Resolving Inside Khronos for now.

**Comment by gnl21** [comment] 2019-08-21 16:33
The restriction was intended to be in Vulkan as well but it was left out of the spec. It'll be added back into a future Vulkan spec release.

It is useful for some subgroup algorithms to know that subgroup sizes are a power of two and this is common in hardware implementations. Other implementations can provide subgroups that are power of two sized by either breaking large subgroups into smaller power of two sizes, or by padding up to a power of two size with inactive invocations.

**Closed by gnl21** 2019-08-21 16:33 UTC
Labels: Vulkan
